# Generated by Django 4.0 on 2024-01-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuneTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='imageurl',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='song',
            name='songurl',
            field=models.URLField(default=''),
        ),
    ]
