# Generated by Django 4.0 on 2024-01-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuneTracker', '0002_song_imageurl_song_songurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='imageurl',
            field=models.URLField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='song',
            name='songurl',
            field=models.URLField(default='', max_length=1000),
        ),
    ]
